#!/bin/bash

#Checking to see if Wordpress already exists. If it does then won't copy from /usr/src/ otherwise we will.

if [[ $(find /var/www/$DOCUMENT_ROOT -mindepth 1 ! -name index.html -a ! -name index.nginx-debian.html -a ! -name phpinfo.php -print -quit | wc -l) -ne 0 ]]; then
    echo "Users document root directory not empty. Not touching content."
    exit 0
fi

echo >&2 "Wordpress not found in /var/www/html - copying now..."
tar -xz --strip-components=1 -f /usr/src/wordpress.tar.gz -C /var/www/html/
sed -i 's@id="dbname" type="text" size="25" value=".*"@id="dbname" type="text" size="25" value="'"$WORDPRESS_DB_NAME"'"@g' /var/www/html/wp-admin/setup-config.php
sed -i 's@id="uname" type="text" size="25" value=".*"@id="uname" type="text" size="25" value="'"$WORDPRESS_DB_USER"'"@g' /var/www/html/wp-admin/setup-config.php
sed -i 's@id="pwd" type="text" size="25" value=".*"@id="pwd" type="text" size="25" value="'"$WORDPRESS_DB_PASSWORD"'"@g' /var/www/html/wp-admin/setup-config.php
sed -i 's@id="dbhost" type="text" size="25" value=".*"@id="dbhost" type="text" size="25" value="'"$WORDPRESS_DB_HOST"'"@g' /var/www/html/wp-admin/setup-config.php
unzip /usr/src/ssh-sftp-updater-support.0.7.1.zip -d /var/www/html/wp-content/plugins/
rm /var/www/html/index.html
echo >&2 "Complete! Wordpress has been successfully copied to $(pwd)"
